# Applies the project's warning set to a target.
function(mcp_set_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4)
        if(MCP_WERROR)
            target_compile_options(${target} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if(MCP_WERROR)
            target_compile_options(${target} PRIVATE -Werror)
        endif()
    endif()
endfunction()
